[tool.poetry]
name = "pyprexor"
version = "0.0.0"
description = ""
authors = ["_MircoWave_ <clarknick1990@gmail.com>"]
readme = "README.md"
packages = [{include = "pyprexor"}]

[tool.poetry.dependencies]
python = "^3.11"


[tool.poetry.group.tests.dependencies]
pytest = "^7.4.0"


[tool.poetry.group.mypy.dependencies]
mypy = "^1.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
